version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - variables.env
    volumes:
      - ./storage/local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:8888"
    env_file:
      - variables.env
    volumes:
      - ./storage/pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata: 
  pgadmin-data:
