version: "3.8"

services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./storage/local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: zarudnayakatyaa@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./storage/pgadmin-data:/var/lib/pgadmin

  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: post-service-api
    restart: always
    env_file:
      - variables.env

volumes:
  local_pgdata: 
  pgadmin-data:
